---

- hosts: all
  become: true
  tasks:

    - name: install the apache2 package
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: ensure apache started
      service:
        name: apache2
        state: started
        enabled: yes
